import { BasePart } from "../types";

export const settingsTest = {
  name: 'Chunkies',
  description: 'A test collection',
  width: 1020,
  height: 1020,
};

export const nftsTest: BasePart[] = [
  {
    key: 'xc0ji19gbgq',
    id: 'body',
    type: 'fixed',
    equippable: '*',
    z: 0,
    src: '',
    folderCID: 'QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh',
    parts: [
      {
        id: 'body_0',
        src: 'ipfs://ipfs/QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh/body.svg',
        name: 'body',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'body_1',
        src: 'ipfs://ipfs/QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh/body_epic.svg',
        name: 'body_epic',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'body_2',
        src: 'ipfs://ipfs/QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh/body_legendary.svg',
        name: 'body_legendary',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'body_3',
        src: 'ipfs://ipfs/QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh/body_rare.svg',
        name: 'body_rare',
        type: 'fixed',
        z: 0,
      },
    ],
    preview:
      'https://gateway.pinata.cloud/ipfs/QmTExChjATHPC2Y4Q8pxSBRaekSxhVMyDqVuKrf4R4vNVh/body_legendary.svg',
  },
  {
    key: 'm9lqxafqu5q',
    id: 'head',
    type: 'fixed',
    equippable: '*',
    z: 1,
    src: '',
    folderCID: 'QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF',
    parts: [
      {
        id: 'head_0',
        src: 'ipfs://ipfs/QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF/0000_head_common.svg',
        name: '0000_head_common',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'head_1',
        src: 'ipfs://ipfs/QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF/0001_head_rare.svg',
        name: '0001_head_rare',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'head_2',
        src: 'ipfs://ipfs/QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF/0002_head_epic.svg',
        name: '0002_head_epic',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'head_3',
        src: 'ipfs://ipfs/QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF/0003_head_legendary.svg',
        name: '0003_head_legendary',
        type: 'fixed',
        z: 0,
      },
    ],
    preview:
      'https://gateway.pinata.cloud/ipfs/QmQbpuw7bFS3mbCtc4xN1aBywcMziNGa77bK9GVuaERVmF/0001_head_rare.svg',
  },
  {
    key: 'rksmcfkiari',
    id: 'hand_left',
    type: 'slot',
    equippable: '*',
    z: 3,
    src: '',
    folderCID: 'QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi',
    parts: [
      {
        id: 'hand_left_0',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/bone_left.svg',
        name: 'bone_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_1',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/bone_right.svg',
        name: 'bone_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_2',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/flag_left.svg',
        name: 'flag_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_3',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/flag_right.svg',
        name: 'flag_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_4',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/pencil_left.svg',
        name: 'pencil_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_5',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/pencil_right.svg',
        name: 'pencil_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_6',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/spear_left.svg',
        name: 'spear_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_left_7',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/spear_right.svg',
        name: 'spear_right',
        type: 'slot',
        z: 0,
      },
    ],
    preview:
      'https://gateway.pinata.cloud/ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/spear_left.svg',
  },
  {
    key: '8mv2bualca7',
    id: 'hand_right',
    type: 'slot',
    equippable: '*',
    z: 4,
    src: '',
    folderCID: 'QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi',
    parts: [
      {
        id: 'hand_right_0',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/bone_left.svg',
        name: 'bone_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_1',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/bone_right.svg',
        name: 'bone_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_2',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/flag_left.svg',
        name: 'flag_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_3',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/flag_right.svg',
        name: 'flag_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_4',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/pencil_left.svg',
        name: 'pencil_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_5',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/pencil_right.svg',
        name: 'pencil_right',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_6',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/spear_left.svg',
        name: 'spear_left',
        type: 'slot',
        z: 0,
      },
      {
        id: 'hand_right_7',
        src: 'ipfs://ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/spear_right.svg',
        name: 'spear_right',
        type: 'slot',
        z: 0,
      },
    ],
    preview:
      'https://gateway.pinata.cloud/ipfs/QmcjzMokrHxzo7W1bC8UwzfLMgz4v5ighGwddfyyZKcGfi/pencil_right.svg',
  },
  {
    key: 'oun8cua6cq',
    id: 'hands',
    type: 'fixed',
    equippable: '*',
    z: 4,
    src: '',
    folderCID: 'QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF',
    parts: [
      {
        id: 'hands_0',
        src: 'ipfs://ipfs/QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF/0000_hand_common.svg',
        name: '0000_hand_common',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'hands_1',
        src: 'ipfs://ipfs/QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF/0001_hand_rare.svg',
        name: '0001_hand_rare',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'hands_2',
        src: 'ipfs://ipfs/QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF/0002_hand_epic.svg',
        name: '0002_hand_epic',
        type: 'fixed',
        z: 0,
      },
      {
        id: 'hands_3',
        src: 'ipfs://ipfs/QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF/0003_hand_legendary.svg',
        name: '0003_hand_legendary',
        type: 'fixed',
        z: 0,
      },
    ],
    preview:
      'https://gateway.pinata.cloud/ipfs/QmSWa3PcwSP5d3GjKoqr2ez92hMzxJuTKwj7miVpmCnPuF/0001_hand_rare.svg',
  },
];
